-- DROP TABLE IF EXISTS public."Emp_Leaves";

CREATE TABLE IF NOT EXISTS public."Emp_Leaves"
(
    "Emp_Leave_Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Employee_Id" integer NOT NULL,
    "Applied_on" date NOT NULL,
    "Leave_date" date NOT NULL,
    "Leave_code" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Emp_Leaves_pkey" PRIMARY KEY ("Emp_Leave_Id"),
    CONSTRAINT unique_pk UNIQUE ("Emp_Leave_Id")
        INCLUDE("Emp_Leave_Id"),
    CONSTRAINT empid_fk FOREIGN KEY ("Employee_Id")
        REFERENCES public."Employee_table" ("Employee_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT leavecode_fk FOREIGN KEY ("Leave_code")
        REFERENCES public."Leaves_table" ("Leave_code") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)